# Generated by Django 5.1.4 on 2026-02-19 01:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("hardware", "Hardware"),
                            ("fee", "Fee"),
                            ("discount", "Discount"),
                            ("credit", "Credit"),
                        ],
                        default="service",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "unit_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. per user, per device, per domain",
                        max_length=64,
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("per_month", "Monthly"),
                            ("per_year", "Annually"),
                            ("per_week", "Weekly"),
                            ("per_quarter", "Quarterly"),
                        ],
                        default="per_month",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="CAD", max_length=8)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="commerce_ca_name_62dcd0_idx"),
                    models.Index(
                        fields=["item_type", "cost_type"],
                        name="commerce_ca_item_ty_2e95e8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BundleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=12
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="commerce.catalogbundle",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commerce.catalogitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="CAD", max_length=8)),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0500"), max_digits=6
                    ),
                ),
                (
                    "company_object_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_by_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_name", models.CharField(max_length=255)),
                ("accepted_email", models.EmailField(blank=True, max_length=254)),
                (
                    "accepted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("signature_meta", models.JSONField(blank=True, default=dict)),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptance",
                        to="commerce.quote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("per_month", "Monthly"),
                            ("per_year", "Annually"),
                            ("per_week", "Weekly"),
                            ("per_quarter", "Quarterly"),
                        ],
                        default="per_month",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=12
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("is_selected", models.BooleanField(default=True)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                ("rule_context", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commerce.catalogitem",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="commerce.quoteline",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="commerce.quote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="commerce.quote",
                    ),
                ),
            ],
        ),
    ]
