# Generated by Django 5.1.4 on 2026-02-19 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0001_initial"),
        ("common", "0003_badge_gamificationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogbundle",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="common.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="common.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quote",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="common.organization",
            ),
            preserve_default=False,
        ),
    ]
