# Generated by Django 5.1.4 on 2026-02-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_catalogbundle_org_catalogitem_org_quote_org"),
        ("common", "0003_badge_gamificationlog"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="catalogitem",
            name="commerce_ca_name_62dcd0_idx",
        ),
        migrations.RemoveIndex(
            model_name="catalogitem",
            name="commerce_ca_item_ty_2e95e8_idx",
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="sku",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Internal SKU / product code. Optional, but recommended for stable imports.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("sku__isnull", False), models.Q(("sku", ""), _negated=True)
                ),
                fields=("org", "sku"),
                name="uniq_commerce_catalogitem_org_sku",
            ),
        ),
    ]
